[phases.setup]
commands = []

[phases.install]
working_directory = "backend"
commands = ["pip install -r requirements.txt"]

[phases.start]
working_directory = "backend"
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
