[phases.setup]
commands = ["cd backend"]

[phases.install]
commands = ["pip install -r requirements.txt"]

[phases.build]
commands = []

[phases.start]
commands = ["uvicorn main:app --host 0.0.0.0 --port $PORT"]
